trigger:
- master

pool:
  vmImage: 'mcr.microsoft.com/windows/servercore:ltsc2019'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Set-ExecutionPolicy AllSigned -Scope Process -Force
      iex ((New-Object System.Net.WebClient).DownloadString('https://download.srcclr.com/ci.ps1'))
      srcclr scan $(Build.SourcesDirectory) --debug --allow-dirty
      