trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Bash@3
  env: {SRCCLR_API_TOKEN: $(SRCCLR_API_TOKEN)}
  inputs:
    targetType: 'inline'
    script: 'curl -sSL https://download.sourceclear.com/ci.sh | bash -s – scan $(Build.SourcesDirectory)'

