trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: PowerShell@2
  env: ${SRCCLR_API_TOKEN}
  inputs:
    targetType: 'inline'
    script: |
      Set-ExecutionPolicy AllSigned -Scope Process -Force
      iex ((New-Object System.Net.WebClient).DownloadString('https://download.srcclr.com/ci.ps1'))
      (Get-Command srcclr).Path
      srcclr scan $(Build.SourcesDirectory) --debug --allow-dirty
      
